# cockpit session name
app.name: UNESCO Data Portal

# cockpit session name
session.name: mysession

# define the languages you want to manage
languages:
    fr: French
    en: English

database:
    server: mongodb://127.0.0.1:27017
    options:
        db: cockpitdb
